# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image as the base image
FROM node:16-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package.json package-lock.json ./

# Install the dependencies, including development dependencies
RUN npm install

# Copy the TypeScript source code
COPY src ./src

# Copy the TypeScript configuration file
COPY tsconfig.json ./

# Build the TypeScript code
RUN npm run build

# Use a lightweight Node.js image for the production environment
FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the build output and package.json file from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./

# Install only production dependencies
RUN npm ci --only=production

# Set environment variables for n8n connection
ENV N8N_HOST=https://your-n8n-instance.com
ENV N8N_API_KEY=your-api-key-here

# Expose a port if necessary (not specified in the README)
# EXPOSE 3000

# Start the application
CMD ["node", "build/index.js"]
